# Site settings
email: ranjps2015@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Data Discoveries
description: Exploring my passions through data and discussion
url: ""
twitter_username: 
default_img: 

# Profile settings
name: RJ Singh
profile_img: 
profile: 
social: https://www.linkedin.com/in/rjsingh
  github: https://github.com/rjs2015

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
